Exception on /v1/individuals/P001 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/decorator.py", line 48, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/uri_parsing.py", line 143, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/validation.py", line 347, in wrapper
    return function(request)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/response.py", line 109, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/parameter.py", line 126, in wrapper
    return function(**kwargs)
TypeError: get_one_individual() got an unexpected keyword argument 'individual_id'
{"timestamp": "2019-08-26 16:01:42.463441", "method": "GET", "path": "/v1/individuals/P001?", "data": "b''", "address": "172.25.0.1", "headers": "Host: localhost:3000\r\nConnection: keep-alive\r\nAccept: application/json\r\nUser-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Safari/605.1.15\r\nAccept-Language: en-ca\r\nReferer: http://localhost:3000/v1/ui/\r\nAccept-Encoding: gzip, deflate\r\n\r\n"}
Checking auth...
{
  "input": {
    "user": "alice",
    "path": [
      "individuals",
      "P001"
    ],
    "method": "GET",
    "token": {
      "payload": {
        "researcher": true,
        "entitlements": [
          "primary",
          "secondaryA"
        ]
      }
    }
  }
}
Failed to parse: //['individuals', 'P001']
{"timestamp": "2019-08-26 16:19:12.899470", "method": "GET", "path": "/v1/individuals/P001?", "data": "b''", "address": "172.26.0.1", "headers": "Host: localhost:3000\r\nConnection: keep-alive\r\nAccept: application/json\r\nUser-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Safari/605.1.15\r\nAccept-Language: en-ca\r\nReferer: http://localhost:3000/v1/ui/\r\nAccept-Encoding: gzip, deflate\r\n\r\n"}
Checking auth...
{
  "input": {
    "user": "alice",
    "path": [
      "individuals",
      "P001"
    ],
    "method": "GET",
    "token": {
      "payload": {
        "researcher": true,
        "entitlements": [
          "primary",
          "secondaryA"
        ]
      }
    }
  }
}
Failed to parse: //['individuals', 'P001']
{"timestamp": "2019-08-26 17:17:24.002107", "method": "GET", "path": "/v1/individuals/P001?", "data": "b''", "address": "172.26.0.1", "headers": "Host: localhost:3000\r\nConnection: keep-alive\r\nAccept: application/json\r\nUser-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Safari/605.1.15\r\nAccept-Language: en-ca\r\nReferer: http://localhost:3000/v1/ui/\r\nAccept-Encoding: gzip, deflate\r\n\r\n"}
Checking auth...
{
  "input": {
    "user": "alice",
    "path": [
      "individuals",
      "P001"
    ],
    "method": "GET",
    "token": {
      "payload": {
        "researcher": true,
        "entitlements": [
          "primary",
          "secondaryA"
        ]
      }
    }
  }
}
Failed to parse: //['individuals', 'P001']
{"timestamp": "2019-08-26 17:17:27.956197", "method": "GET", "path": "/v1/individuals/P001?", "data": "b''", "address": "172.26.0.1", "headers": "Host: localhost:3000\r\nConnection: keep-alive\r\nAccept: application/json\r\nUser-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Safari/605.1.15\r\nAccept-Language: en-ca\r\nReferer: http://localhost:3000/v1/ui/\r\nAccept-Encoding: gzip, deflate\r\n\r\n"}
Checking auth...
{
  "input": {
    "user": "alice",
    "path": [
      "individuals",
      "P001"
    ],
    "method": "GET",
    "token": {
      "payload": {
        "researcher": true,
        "entitlements": [
          "primary",
          "secondaryA"
        ]
      }
    }
  }
}
Failed to parse: //['individuals', 'P001']
{"timestamp": "2019-08-26 17:22:57.528513", "method": "GET", "path": "/v1/individuals/P001?", "data": "b''", "address": "172.27.0.1", "headers": "Host: localhost:3000\r\nConnection: keep-alive\r\nAccept: application/json\r\nUser-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Safari/605.1.15\r\nAccept-Language: en-ca\r\nReferer: http://localhost:3000/v1/ui/\r\nAccept-Encoding: gzip, deflate\r\n\r\n"}
Checking auth...
{
  "input": {
    "user": "alice",
    "path": [
      "individuals",
      "P001"
    ],
    "method": "GET",
    "token": {
      "payload": {
        "researcher": true,
        "entitlements": [
          "primary",
          "secondaryA"
        ]
      }
    }
  }
}
Auth response:
{}
{"timestamp": "2019-08-26 17:23:08.409811", "method": "GET", "path": "/v1/individuals/P001?", "data": "b''", "address": "172.27.0.1", "headers": "Host: localhost:3000\r\nConnection: keep-alive\r\nAccept: application/json\r\nUser-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Safari/605.1.15\r\nAccept-Language: en-ca\r\nReferer: http://localhost:3000/v1/ui/\r\nAccept-Encoding: gzip, deflate\r\n\r\n"}
Checking auth...
{
  "input": {
    "user": "alice",
    "path": [
      "individuals",
      "P001"
    ],
    "method": "GET",
    "token": {
      "payload": {
        "researcher": true,
        "entitlements": [
          "primary",
          "secondaryA"
        ]
      }
    }
  }
}
Auth response:
{}
{"timestamp": "2019-08-26 17:24:54.952954", "method": "GET", "path": "/v1/individuals/P001?", "data": "b''", "address": "172.27.0.1", "headers": "Host: localhost:3000\r\nConnection: keep-alive\r\nAccept: application/json\r\nUser-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Safari/605.1.15\r\nAccept-Language: en-ca\r\nReferer: http://localhost:3000/v1/ui/\r\nAccept-Encoding: gzip, deflate\r\n\r\n"}
Checking auth...
{
  "input": {
    "user": "alice",
    "path": [
      "individuals",
      "P001"
    ],
    "method": "GET",
    "token": {
      "payload": {
        "researcher": true,
        "entitlements": [
          "primary",
          "secondaryA"
        ]
      }
    }
  }
}
Auth response:
{
  "result": true
}
Exception on /v1/individuals/P001 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/decorator.py", line 48, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/uri_parsing.py", line 143, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/validation.py", line 347, in wrapper
    return function(request)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/response.py", line 109, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/parameter.py", line 126, in wrapper
    return function(**kwargs)
  File "</usr/local/lib/python3.7/site-packages/decorator.py:decorator-gen-3>", line 2, in get_one_individual
  File "/usr/local/lib/python3.7/site-packages/sql_clinical-0.1.1-py3.7.egg/sql_clinical/api/logging.py", line 59, in apilog
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/sql_clinical-0.1.1-py3.7.egg/sql_clinical/api/operations.py", line 109, in get_one_individual
    if j.get("allow", False):
AttributeError: 'bool' object has no attribute 'get'
{"timestamp": "2019-08-26 17:28:14.465731", "method": "GET", "path": "/v1/individuals/P001?", "data": "b''", "address": "172.28.0.1", "headers": "Host: localhost:3000\r\nConnection: keep-alive\r\nAccept: application/json\r\nUser-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Safari/605.1.15\r\nAccept-Language: en-ca\r\nReferer: http://localhost:3000/v1/ui/\r\nAccept-Encoding: gzip, deflate\r\n\r\n"}
Checking auth...
{
  "input": {
    "user": "alice",
    "path": [
      "individuals",
      "P001"
    ],
    "method": "GET",
    "token": {
      "payload": {
        "researcher": true,
        "entitlements": [
          "primary",
          "secondaryA"
        ]
      }
    }
  }
}
Auth response:
{
  "result": true
}
Exception on /v1/individuals/P001 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/decorator.py", line 48, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/uri_parsing.py", line 143, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/validation.py", line 347, in wrapper
    return function(request)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/response.py", line 109, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/parameter.py", line 126, in wrapper
    return function(**kwargs)
  File "</usr/local/lib/python3.7/site-packages/decorator.py:decorator-gen-3>", line 2, in get_one_individual
  File "/usr/local/lib/python3.7/site-packages/sql_clinical-0.1.1-py3.7.egg/sql_clinical/api/logging.py", line 59, in apilog
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/sql_clinical-0.1.1-py3.7.egg/sql_clinical/api/operations.py", line 109, in get_one_individual
    if "allow" in j and j["allow"]:
TypeError: argument of type 'bool' is not iterable
{"timestamp": "2019-08-26 17:34:02.675083", "method": "GET", "path": "/v1/individuals/P001?", "data": "b''", "address": "172.30.0.1", "headers": "Host: localhost:3000\r\nConnection: keep-alive\r\nAccept: application/json\r\nUser-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Safari/605.1.15\r\nAccept-Language: en-ca\r\nReferer: http://localhost:3000/v1/ui/\r\nAccept-Encoding: gzip, deflate\r\n\r\n"}
Checking auth...
{
  "input": {
    "user": "alice",
    "path": [
      "individuals",
      "P001"
    ],
    "method": "GET",
    "token": {
      "payload": {
        "researcher": true,
        "entitlements": [
          "primary",
          "secondaryA"
        ]
      }
    }
  }
}
Auth response:
{
  "result": true
}
Get One Individual: Authz success.
Exception on /v1/individuals/P001 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/decorator.py", line 48, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/uri_parsing.py", line 143, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/validation.py", line 347, in wrapper
    return function(request)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/response.py", line 109, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/parameter.py", line 126, in wrapper
    return function(**kwargs)
TypeError: get_one_individual() missing 1 required positional argument: 'token'
{"timestamp": "2019-10-01 19:54:15.399773", "method": "GET", "path": "/v1/individuals/P001?token=eyJhbGciOiJIUzI1NiJ9.eyJyZXNlYXJjaGVyIjp0cnVlLCJlbnRpdGxlbWVudHMiOlsicHJpbWFyeSIsInNlY29uZGFyeUEiXX0.yDbbS2IDlM8WdXD48o8m2yVcpVqkOMauAh4vRiOWzdU", "data": "b''", "address": "172.22.0.1", "headers": "Host: localhost:3000\r\nUser-Agent: curl/7.54.0\r\nAccept: */*\r\n\r\n"}
Checking auth...
{
  "input": {
    "user": "alice",
    "path": [
      "individuals",
      "P001"
    ],
    "method": "GET",
    "token": "eyJhbGciOiJIUzI1NiJ9.eyJyZXNlYXJjaGVyIjp0cnVlLCJlbnRpdGxlbWVudHMiOlsicHJpbWFyeSIsInNlY29uZGFyeUEiXX0.yDbbS2IDlM8WdXD48o8m2yVcpVqkOMauAh4vRiOWzdU"
  }
}
Auth response:
{
  "result": false
}
Exception on /v1/individuals/P001 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/decorator.py", line 48, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/uri_parsing.py", line 143, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/validation.py", line 347, in wrapper
    return function(request)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/response.py", line 109, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/parameter.py", line 126, in wrapper
    return function(**kwargs)
TypeError: get_one_individual() missing 1 required positional argument: 'token'
{"timestamp": "2019-10-01 19:55:57.555542", "method": "GET", "path": "/v1/individuals/P001?token=eyJhbGciOiJIUzI1NiJ9.eyJyZXNlYXJjaGVyIjp0cnVlLCJlbnRpdGxlbWVudHMiOlsicHJpbWFyeSIsInNlY29uZGFyeUEiXX0.yDbbS2IDlM8WdXD48o8m2yVcpVqkOMauAh4vRiOWzdU", "data": "b''", "address": "172.22.0.1", "headers": "Host: localhost:3000\r\nUser-Agent: curl/7.54.0\r\nAccept: */*\r\n\r\n"}
Checking auth...
{
  "input": {
    "user": "alice",
    "path": [
      "individuals",
      "P001"
    ],
    "method": "GET",
    "token": "eyJhbGciOiJIUzI1NiJ9.eyJyZXNlYXJjaGVyIjp0cnVlLCJlbnRpdGxlbWVudHMiOlsicHJpbWFyeSIsInNlY29uZGFyeUEiXX0.yDbbS2IDlM8WdXD48o8m2yVcpVqkOMauAh4vRiOWzdU"
  }
}
Auth response:
{
  "result": false
}
{"timestamp": "2019-10-01 21:58:18.054631", "method": "GET", "path": "/v1/individuals/P001?token=eyJhbGciOiJIUzI1NiJ9.eyJyZXNlYXJjaGVyIjp0cnVlLCJlbnRpdGxlbWVudHMiOlsicHJpbWFyeSIsInNlY29uZGFyeUEiXX0.yDbbS2IDlM8WdXD48o8m2yVcpVqkOMauAh4vRiOWzdU", "data": "b''", "address": "172.18.0.1", "headers": "Host: localhost:3000\r\nUser-Agent: curl/7.54.0\r\nAccept: */*\r\n\r\n"}
Checking auth...
{
  "input": {
    "user": "alice",
    "path": [
      "individuals",
      "P001"
    ],
    "method": "GET",
    "token": "eyJhbGciOiJIUzI1NiJ9.eyJyZXNlYXJjaGVyIjp0cnVlLCJlbnRpdGxlbWVudHMiOlsicHJpbWFyeSIsInNlY29uZGFyeUEiXX0.yDbbS2IDlM8WdXD48o8m2yVcpVqkOMauAh4vRiOWzdU"
  }
}
Auth response:
{
  "result": true
}
Get One Individual: Authz success.
{"timestamp": "2019-10-01 21:58:32.565070", "method": "GET", "path": "/v1/individuals/P001?token=eyJhbGciOiJIUzI1NiJ9.eyJyZXNlYXJjaGVyIjp0cnVlLCJlbnRpdGxlbWVudHMiOlsic2Vjb25kYXJ5QiJdfQ.gLDeEfENzd6IAtwuPHQhILl0yfxQLM6ar01nn-vyvOg", "data": "b''", "address": "172.18.0.1", "headers": "Host: localhost:3000\r\nUser-Agent: curl/7.54.0\r\nAccept: */*\r\n\r\n"}
Checking auth...
{
  "input": {
    "user": "alice",
    "path": [
      "individuals",
      "P001"
    ],
    "method": "GET",
    "token": "eyJhbGciOiJIUzI1NiJ9.eyJyZXNlYXJjaGVyIjp0cnVlLCJlbnRpdGxlbWVudHMiOlsic2Vjb25kYXJ5QiJdfQ.gLDeEfENzd6IAtwuPHQhILl0yfxQLM6ar01nn-vyvOg"
  }
}
Auth response:
{
  "result": false
}
{"timestamp": "2019-10-02 17:16:52.953207", "method": "GET", "path": "/v1/individuals/P001?", "data": "b''", "address": "172.19.0.1", "headers": "Host: localhost:3000\r\nUser-Agent: curl/7.54.0\r\nAccept: */*\r\nAuthorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyZXNlYXJjaGVyIjp0cnVlLCJlbnRpdGxlbWVudHMiOlsicHJpbWFyeSIsInNlY29uZGFyeUEiXX0.yDbbS2IDlM8WdXD48o8m2yVcpVqkOMauAh4vRiOWzdU\r\n\r\n"}
Exception on /v1/individuals/P001 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/decorator.py", line 48, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/uri_parsing.py", line 143, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/validation.py", line 347, in wrapper
    return function(request)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/response.py", line 109, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/parameter.py", line 126, in wrapper
    return function(**kwargs)
  File "</usr/local/lib/python3.7/site-packages/decorator.py:decorator-gen-3>", line 2, in get_one_individual
  File "/usr/local/lib/python3.7/site-packages/sql_clinical-0.1.1-py3.7.egg/sql_clinical/api/logging.py", line 59, in apilog
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/sql_clinical-0.1.1-py3.7.egg/sql_clinical/api/operations.py", line 136, in get_one_individual
    response = check_opa_authz(url, user, "GET", path)
  File "/usr/local/lib/python3.7/site-packages/sql_clinical-0.1.1-py3.7.egg/sql_clinical/api/operations.py", line 91, in check_opa_authz
    token = _get_token()
  File "/usr/local/lib/python3.7/site-packages/sql_clinical-0.1.1-py3.7.egg/sql_clinical/api/operations.py", line 70, in _get_token
    if parts <= 1:
TypeError: '<=' not supported between instances of 'list' and 'int'
{"timestamp": "2019-10-02 17:19:44.706026", "method": "GET", "path": "/v1/individuals/P001?", "data": "b''", "address": "172.20.0.1", "headers": "Host: localhost:3000\r\nUser-Agent: curl/7.54.0\r\nAccept: */*\r\nAuthorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyZXNlYXJjaGVyIjp0cnVlLCJlbnRpdGxlbWVudHMiOlsicHJpbWFyeSIsInNlY29uZGFyeUEiXX0.yDbbS2IDlM8WdXD48o8m2yVcpVqkOMauAh4vRiOWzdU\r\n\r\n"}
Checking auth...
{
  "input": {
    "user": "alice",
    "path": [
      "individuals",
      "P001"
    ],
    "method": "GET",
    "token": "eyJhbGciOiJIUzI1NiJ9.eyJyZXNlYXJjaGVyIjp0cnVlLCJlbnRpdGxlbWVudHMiOlsicHJpbWFyeSIsInNlY29uZGFyeUEiXX0.yDbbS2IDlM8WdXD48o8m2yVcpVqkOMauAh4vRiOWzdU"
  }
}
Auth response:
{
  "result": true
}
Get One Individual: Authz success.
{"timestamp": "2019-10-02 17:19:53.514025", "method": "GET", "path": "/v1/individuals/P001?", "data": "b''", "address": "172.20.0.1", "headers": "Host: localhost:3000\r\nUser-Agent: curl/7.54.0\r\nAccept: */*\r\nAuthorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyZXNlYXJjaGVyIjp0cnVlLCJlbnRpdGxlbWVudHMiOlsic2Vjb25kYXJ5QiJdfQ.gLDeEfENzd6IAtwuPHQhILl0yfxQLM6ar01nn-vyvOg\r\n\r\n"}
Checking auth...
{
  "input": {
    "user": "alice",
    "path": [
      "individuals",
      "P001"
    ],
    "method": "GET",
    "token": "eyJhbGciOiJIUzI1NiJ9.eyJyZXNlYXJjaGVyIjp0cnVlLCJlbnRpdGxlbWVudHMiOlsic2Vjb25kYXJ5QiJdfQ.gLDeEfENzd6IAtwuPHQhILl0yfxQLM6ar01nn-vyvOg"
  }
}
Auth response:
{
  "result": false
}
{"timestamp": "2019-10-02 21:52:08.045940", "method": "GET", "path": "/v1/individuals/P001?", "data": "b''", "address": "172.22.0.1", "headers": "Host: localhost:3000\r\nUser-Agent: curl/7.54.0\r\nAccept: */*\r\nAuthorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyZXNlYXJjaGVyIjp0cnVlLCJlbnRpdGxlbWVudHMiOlsic2Vjb25kYXJ5QiJdfQ.gLDeEfENzd6IAtwuPHQhILl0yfxQLM6ar01nn-vyvOg\r\nX-Claim-Profyle-Member: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm9meWxlX21lbWJlciI6dHJ1ZX0._F_NrUiizHfMK-WfndieZULnqI5i_kXWfb2FIOMpqVs\r\n\r\n"}
Checking auth...
{
  "input": {
    "user": "alice",
    "path": [
      "individuals",
      "P001"
    ],
    "method": "GET",
    "id_token": "eyJhbGciOiJIUzI1NiJ9.eyJyZXNlYXJjaGVyIjp0cnVlLCJlbnRpdGxlbWVudHMiOlsic2Vjb25kYXJ5QiJdfQ.gLDeEfENzd6IAtwuPHQhILl0yfxQLM6ar01nn-vyvOg"
  }
}
Auth response:
{
  "result": false
}
{"timestamp": "2019-10-02 21:52:20.347553", "method": "GET", "path": "/v1/individuals/P001?", "data": "b''", "address": "172.22.0.1", "headers": "Host: localhost:3000\r\nUser-Agent: curl/7.54.0\r\nAccept: */*\r\nAuthorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzNDU2Nzg5MDEyIiwibmFtZSI6IkNhcm9sIiwiaWF0IjoxNTE2MjM5MDIyLCJyZXNlYXJjaGVyIjp0cnVlfQ.bV_qyrbL15GiG7CZgKgzxGAMOl0MFhJTyYUoxxMkXB8\r\nX-Claim-Profyle-Member: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm9meWxlX21lbWJlciI6dHJ1ZX0._F_NrUiizHfMK-WfndieZULnqI5i_kXWfb2FIOMpqVs\r\n\r\n"}
Checking auth...
{
  "input": {
    "user": "alice",
    "path": [
      "individuals",
      "P001"
    ],
    "method": "GET",
    "id_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzNDU2Nzg5MDEyIiwibmFtZSI6IkNhcm9sIiwiaWF0IjoxNTE2MjM5MDIyLCJyZXNlYXJjaGVyIjp0cnVlfQ.bV_qyrbL15GiG7CZgKgzxGAMOl0MFhJTyYUoxxMkXB8"
  }
}
Auth response:
{
  "result": false
}
{"timestamp": "2019-10-02 21:52:29.078637", "method": "GET", "path": "/v1/individuals/P001?", "data": "b''", "address": "172.22.0.1", "headers": "Host: localhost:3000\r\nUser-Agent: curl/7.54.0\r\nAccept: */*\r\nAuthorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkFsaWNlIiwiaWF0IjoxNTE2MjM5MDIyLCJyZXNlYXJjaGVyIjp0cnVlfQ.6PFJ_2d-IZYexlf2YFwRrT5rD8foqGePYAOMQSPwUaI\r\nX-Claim-Profyle-Member: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm9meWxlX21lbWJlciI6dHJ1ZX0._F_NrUiizHfMK-WfndieZULnqI5i_kXWfb2FIOMpqVs\r\n\r\n"}
Checking auth...
{
  "input": {
    "user": "alice",
    "path": [
      "individuals",
      "P001"
    ],
    "method": "GET",
    "id_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkFsaWNlIiwiaWF0IjoxNTE2MjM5MDIyLCJyZXNlYXJjaGVyIjp0cnVlfQ.6PFJ_2d-IZYexlf2YFwRrT5rD8foqGePYAOMQSPwUaI"
  }
}
Auth response:
{
  "result": false
}
{"timestamp": "2019-10-02 21:55:54.290900", "method": "GET", "path": "/v1/individuals/P001?", "data": "b''", "address": "172.23.0.1", "headers": "Host: localhost:3000\r\nUser-Agent: curl/7.54.0\r\nAccept: */*\r\nAuthorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkFsaWNlIiwiaWF0IjoxNTE2MjM5MDIyLCJyZXNlYXJjaGVyIjp0cnVlfQ.6PFJ_2d-IZYexlf2YFwRrT5rD8foqGePYAOMQSPwUaI\r\nX-Claim-Profyle-Member: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm9meWxlX21lbWJlciI6dHJ1ZX0._F_NrUiizHfMK-WfndieZULnqI5i_kXWfb2FIOMpqVs\r\n\r\n"}
[]
Checking auth...
{
  "input": {
    "user": "alice",
    "path": [
      "individuals",
      "P001"
    ],
    "method": "GET",
    "id_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkFsaWNlIiwiaWF0IjoxNTE2MjM5MDIyLCJyZXNlYXJjaGVyIjp0cnVlfQ.6PFJ_2d-IZYexlf2YFwRrT5rD8foqGePYAOMQSPwUaI"
  }
}
Auth response:
{
  "result": false
}
{"timestamp": "2019-10-02 22:00:11.657102", "method": "GET", "path": "/v1/individuals/P001?", "data": "b''", "address": "172.24.0.1", "headers": "Host: localhost:3000\r\nUser-Agent: curl/7.54.0\r\nAccept: */*\r\nAuthorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkFsaWNlIiwiaWF0IjoxNTE2MjM5MDIyLCJyZXNlYXJjaGVyIjp0cnVlfQ.6PFJ_2d-IZYexlf2YFwRrT5rD8foqGePYAOMQSPwUaI\r\nX-Claim-Profyle-Member: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm9meWxlX21lbWJlciI6dHJ1ZX0._F_NrUiizHfMK-WfndieZULnqI5i_kXWfb2FIOMpqVs\r\n\r\n"}
Exception on /v1/individuals/P001 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/decorator.py", line 48, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/uri_parsing.py", line 143, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/validation.py", line 347, in wrapper
    return function(request)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/response.py", line 109, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/parameter.py", line 126, in wrapper
    return function(**kwargs)
  File "</usr/local/lib/python3.7/site-packages/decorator.py:decorator-gen-3>", line 2, in get_one_individual
  File "/usr/local/lib/python3.7/site-packages/sql_clinical-0.1.1-py3.7.egg/sql_clinical/api/logging.py", line 59, in apilog
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/sql_clinical-0.1.1-py3.7.egg/sql_clinical/api/operations.py", line 153, in get_one_individual
    response = check_opa_authz(url, user, "GET", path)
  File "/usr/local/lib/python3.7/site-packages/sql_clinical-0.1.1-py3.7.egg/sql_clinical/api/operations.py", line 107, in check_opa_authz
    claims_tokens = _get_claims_tokens()
  File "/usr/local/lib/python3.7/site-packages/sql_clinical-0.1.1-py3.7.egg/sql_clinical/api/operations.py", line 80, in _get_claims_tokens
    logger().info(json.dumps(request.headers, indent=2))
  File "/usr/local/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/local/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type EnvironHeaders is not JSON serializable
{"timestamp": "2019-10-02 22:02:33.381826", "method": "GET", "path": "/v1/individuals/P001?", "data": "b''", "address": "172.24.0.1", "headers": "Host: localhost:3000\r\nUser-Agent: curl/7.54.0\r\nAccept: */*\r\nAuthorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkFsaWNlIiwiaWF0IjoxNTE2MjM5MDIyLCJyZXNlYXJjaGVyIjp0cnVlfQ.6PFJ_2d-IZYexlf2YFwRrT5rD8foqGePYAOMQSPwUaI\r\nX-Claim-Profyle-Member: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm9meWxlX21lbWJlciI6dHJ1ZX0._F_NrUiizHfMK-WfndieZULnqI5i_kXWfb2FIOMpqVs\r\n\r\n"}
Exception on /v1/individuals/P001 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/decorator.py", line 48, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/uri_parsing.py", line 143, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/validation.py", line 347, in wrapper
    return function(request)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/response.py", line 109, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.7/site-packages/connexion/decorators/parameter.py", line 126, in wrapper
    return function(**kwargs)
  File "</usr/local/lib/python3.7/site-packages/decorator.py:decorator-gen-3>", line 2, in get_one_individual
  File "/usr/local/lib/python3.7/site-packages/sql_clinical-0.1.1-py3.7.egg/sql_clinical/api/logging.py", line 59, in apilog
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/sql_clinical-0.1.1-py3.7.egg/sql_clinical/api/operations.py", line 153, in get_one_individual
    response = check_opa_authz(url, user, "GET", path)
  File "/usr/local/lib/python3.7/site-packages/sql_clinical-0.1.1-py3.7.egg/sql_clinical/api/operations.py", line 107, in check_opa_authz
    claims_tokens = _get_claims_tokens()
  File "/usr/local/lib/python3.7/site-packages/sql_clinical-0.1.1-py3.7.egg/sql_clinical/api/operations.py", line 80, in _get_claims_tokens
    logger().info(json.dumps(request.headers.items(), indent=2))
  File "/usr/local/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/local/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type generator is not JSON serializable
{"timestamp": "2019-10-02 22:06:03.843460", "method": "GET", "path": "/v1/individuals/P001?", "data": "b''", "address": "172.26.0.1", "headers": "Host: localhost:3000\r\nUser-Agent: curl/7.54.0\r\nAccept: */*\r\nAuthorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkFsaWNlIiwiaWF0IjoxNTE2MjM5MDIyLCJyZXNlYXJjaGVyIjp0cnVlfQ.6PFJ_2d-IZYexlf2YFwRrT5rD8foqGePYAOMQSPwUaI\r\nX-Claim-Profyle-Member: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm9meWxlX21lbWJlciI6dHJ1ZX0._F_NrUiizHfMK-WfndieZULnqI5i_kXWfb2FIOMpqVs\r\n\r\n"}
{"Host": "localhost:3000"}
{"User-Agent": "curl/7.54.0"}
{"Accept": "*/*"}
{"Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkFsaWNlIiwiaWF0IjoxNTE2MjM5MDIyLCJyZXNlYXJjaGVyIjp0cnVlfQ.6PFJ_2d-IZYexlf2YFwRrT5rD8foqGePYAOMQSPwUaI"}
{"X-Claim-Profyle-Member": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm9meWxlX21lbWJlciI6dHJ1ZX0._F_NrUiizHfMK-WfndieZULnqI5i_kXWfb2FIOMpqVs"}
[]
Checking auth...
{
  "input": {
    "user": "alice",
    "path": [
      "individuals",
      "P001"
    ],
    "method": "GET",
    "id_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkFsaWNlIiwiaWF0IjoxNTE2MjM5MDIyLCJyZXNlYXJjaGVyIjp0cnVlfQ.6PFJ_2d-IZYexlf2YFwRrT5rD8foqGePYAOMQSPwUaI"
  }
}
Auth response:
{
  "result": false
}
{"timestamp": "2019-10-02 22:07:19.185017", "method": "GET", "path": "/v1/individuals/P001?", "data": "b''", "address": "172.27.0.1", "headers": "Host: localhost:3000\r\nUser-Agent: curl/7.54.0\r\nAccept: */*\r\nAuthorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkFsaWNlIiwiaWF0IjoxNTE2MjM5MDIyLCJyZXNlYXJjaGVyIjp0cnVlfQ.6PFJ_2d-IZYexlf2YFwRrT5rD8foqGePYAOMQSPwUaI\r\nX-Claim-Profyle-Member: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm9meWxlX21lbWJlciI6dHJ1ZX0._F_NrUiizHfMK-WfndieZULnqI5i_kXWfb2FIOMpqVs\r\n\r\n"}
[
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm9meWxlX21lbWJlciI6dHJ1ZX0._F_NrUiizHfMK-WfndieZULnqI5i_kXWfb2FIOMpqVs"
]
Checking auth...
{
  "input": {
    "user": "alice",
    "path": [
      "individuals",
      "P001"
    ],
    "method": "GET",
    "id_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkFsaWNlIiwiaWF0IjoxNTE2MjM5MDIyLCJyZXNlYXJjaGVyIjp0cnVlfQ.6PFJ_2d-IZYexlf2YFwRrT5rD8foqGePYAOMQSPwUaI",
    "claims_tokens": [
      "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm9meWxlX21lbWJlciI6dHJ1ZX0._F_NrUiizHfMK-WfndieZULnqI5i_kXWfb2FIOMpqVs"
    ]
  }
}
Auth response:
{
  "result": true
}
Get One Individual: Authz success.
{"timestamp": "2019-10-02 22:08:33.738209", "method": "GET", "path": "/v1/individuals/P001?", "data": "b''", "address": "172.27.0.1", "headers": "Host: localhost:3000\r\nUser-Agent: curl/7.54.0\r\nAccept: */*\r\nAuthorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkFsaWNlIiwiaWF0IjoxNTE2MjM5MDIyLCJyZXNlYXJjaGVyIjp0cnVlfQ.6PFJ_2d-IZYexlf2YFwRrT5rD8foqGePYAOMQSPwUaI\r\nX-Claim-Profyle-Member: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm9meWxlX21lbWJlciI6dHJ1ZX0._F_NrUiizHfMK-WfndieZULnqI5i_kXWfb2FIOMpqVs\r\n\r\n"}
[
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm9meWxlX21lbWJlciI6dHJ1ZX0._F_NrUiizHfMK-WfndieZULnqI5i_kXWfb2FIOMpqVs"
]
Checking auth...
{
  "input": {
    "user": "alice",
    "path": [
      "individuals",
      "P001"
    ],
    "method": "GET",
    "id_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkFsaWNlIiwiaWF0IjoxNTE2MjM5MDIyLCJyZXNlYXJjaGVyIjp0cnVlfQ.6PFJ_2d-IZYexlf2YFwRrT5rD8foqGePYAOMQSPwUaI",
    "claims_tokens": [
      "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm9meWxlX21lbWJlciI6dHJ1ZX0._F_NrUiizHfMK-WfndieZULnqI5i_kXWfb2FIOMpqVs"
    ]
  }
}
Auth response:
{
  "result": true
}
Get One Individual: Authz success.
{"timestamp": "2019-10-02 22:08:42.416862", "method": "GET", "path": "/v1/individuals/P001?", "data": "b''", "address": "172.27.0.1", "headers": "Host: localhost:3000\r\nUser-Agent: curl/7.54.0\r\nAccept: */*\r\nAuthorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkFsaWNlIiwiaWF0IjoxNTE2MjM5MDIyLCJyZXNlYXJjaGVyIjp0cnVlfQ.6PFJ_2d-IZYexlf2YFwRrT5rD8foqGePYAOMQSPwUaI\r\nX-Claim-Profyle-Member: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm9meWxlX21lbWJlciI6ZmFsc2V9.vfz8abmDPcA6bIXWL546xdDBVrK57PasCZVtn-Tudjs\r\n\r\n"}
[
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm9meWxlX21lbWJlciI6ZmFsc2V9.vfz8abmDPcA6bIXWL546xdDBVrK57PasCZVtn-Tudjs"
]
Checking auth...
{
  "input": {
    "user": "alice",
    "path": [
      "individuals",
      "P001"
    ],
    "method": "GET",
    "id_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkFsaWNlIiwiaWF0IjoxNTE2MjM5MDIyLCJyZXNlYXJjaGVyIjp0cnVlfQ.6PFJ_2d-IZYexlf2YFwRrT5rD8foqGePYAOMQSPwUaI",
    "claims_tokens": [
      "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm9meWxlX21lbWJlciI6ZmFsc2V9.vfz8abmDPcA6bIXWL546xdDBVrK57PasCZVtn-Tudjs"
    ]
  }
}
Auth response:
{
  "result": false
}
{"timestamp": "2019-10-02 22:08:56.990037", "method": "GET", "path": "/v1/individuals/P001?", "data": "b''", "address": "172.27.0.1", "headers": "Host: localhost:3000\r\nUser-Agent: curl/7.54.0\r\nAccept: */*\r\nAuthorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkFsaWNlIiwiaWF0IjoxNTE2MjM5MDIyLCJyZXNlYXJjaGVyIjp0cnVlfQ.6PFJ_2d-IZYexlf2YFwRrT5rD8foqGePYAOMQSPwUaI\r\nX-Claim-Profyle-Member: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZjRjbl9tZW1iZXIiOnRydWV9.yGMytTyC0c3Mrfv5Bulm9dW7ZaEALnR3vma3Tuhxd_k\r\n\r\n"}
[
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZjRjbl9tZW1iZXIiOnRydWV9.yGMytTyC0c3Mrfv5Bulm9dW7ZaEALnR3vma3Tuhxd_k"
]
Checking auth...
{
  "input": {
    "user": "alice",
    "path": [
      "individuals",
      "P001"
    ],
    "method": "GET",
    "id_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkFsaWNlIiwiaWF0IjoxNTE2MjM5MDIyLCJyZXNlYXJjaGVyIjp0cnVlfQ.6PFJ_2d-IZYexlf2YFwRrT5rD8foqGePYAOMQSPwUaI",
    "claims_tokens": [
      "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZjRjbl9tZW1iZXIiOnRydWV9.yGMytTyC0c3Mrfv5Bulm9dW7ZaEALnR3vma3Tuhxd_k"
    ]
  }
}
Auth response:
{
  "result": false
}
